name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-model-training
      - feature-api
      - feature-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches and history

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Fetch and checkout `main.py` from `feature-model-training`
        run: |
          git checkout origin/feature-model-training -- main.py

      - name: Fetch and checkout `app.py` from `feature-api`
        run: |
          git checkout origin/feature-api -- app.py

      - name: Fetch and checkout `test_model.py` from `feature-model-training`
        run: |
          git checkout origin/feature-model-training -- test_model.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint and tests
        run: |
          pylint main.py app.py test.py
          pytest test.py
