name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-model-training
      - feature-api
      - feature-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all branches and history

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Fetch and checkout files from feature-model-training
        run: |
          git checkout origin/feature-model-training -- main.py house_data.csv test.py house_test_data.csv

      - name: Fetch and checkout app.py from feature-api
        run: |
          git checkout origin/feature-api -- app.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model and generate test data
        run: |
          python main.py  # This will train the model using house_data.csv

      - name: Run lint and tests
        run: |
          pylint main.py app.py test.py
          pytest test.py
